dist: xenial
language: c

before_script:
  # install toolchain
  - (! var_search "${TRAVIS_SDK-}" arm || (wget https://s3.amazonaws.com/adafruit-circuit-python/gcc-arm-embedded_7-2018q2-1~xenial1_amd64.deb && sudo dpkg -i gcc-arm-embedded*_amd64.deb))

  # report some good version numbers to the build
  - gcc --version
  - (! var_search "${TRAVIS_SDK-}" arm || arm-none-eabi-gcc --version)
  - python3 --version

  script:
  - make clean
  - make all